kiemketaisan/kiemketaisan/Controllers/NhanVienController.cs
using kiemketaisan.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebGrease.Css.Extensions;

namespace kiemketaisan.Controllers
{
    public class NhanVienController : Controller
    {
        Data db = new Data();
        public ActionResult Index()
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login","Home");
            }
            ViewData["taikhoan"] = db.TaiKhoans.ToList();
            ViewData["phong"] = db.PhongBans.ToList();
            return View(db.ThongTins.ToList());
        }
        public ActionResult Create()
        {
            ViewData["phong"] = db.PhongBans.ToList();
            return View();
        }

        // POST: ThongTins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,HoTen,Email,GioiTinh,NgaySinh,DiaChi,HinhAnh,IdTK,IdPB")] ThongTin thongTin)
        {
            ViewData["phong"] = db.PhongBans.ToList();

            if (ModelState.IsValid)
            {
                TaiKhoan tk = new TaiKhoan();
                tk.PhanQuyen = Convert.ToInt32(Request["phanquyen"]);
                tk.TenDangNhap = Request["tendangnhap"];
                tk.MatKhau = Request["matkhau"];
                db.TaiKhoans.Add(tk);
                db.SaveChanges();
                var f = Request.Files["Anh"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Server.MapPath("~/upload/" + FileName);
                    f.SaveAs(UploadPath);
                    thongTin.HinhAnh = FileName;
                }
                thongTin.IdTK = tk.Id;
                db.ThongTins.Add(thongTin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(thongTin);
        }

        // GET: ThongTins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThongTin thongTin = db.ThongTins.Find(id);
            ViewData["taikhoan"] = db.TaiKhoans.ToList();
            ViewData["phong"] = db.PhongBans.ToList();

            if (thongTin == null)
            {
                return HttpNotFound();
            }
            return View(thongTin);
        }

        // POST: ThongTins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HoTen,Email,GioiTinh,NgaySinh,DiaChi,HinhAnh,IdTK,IdPB")] ThongTin thongTin)
        {
            ViewData["phong"] = db.PhongBans.ToList();

            if (ModelState.IsValid)
            {
                TaiKhoan tk = db.TaiKhoans.FirstOrDefault(g => g.Id == thongTin.IdTK);
                tk.PhanQuyen = Convert.ToInt32(Request["phanquyen"]);
                db.TaiKhoans.AddOrUpdate(tk);
                db.SaveChanges();
                var f = Request.Files["Anh"];
                if (f != null && f.ContentLength > 0)
                {
                    string folderPath = Server.MapPath("~/upload/" + thongTin.HinhAnh);
                    if (System.IO.File.Exists(folderPath))
                    {
                        System.IO.File.Delete(folderPath);
                    }
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Server.MapPath("~/upload/" + FileName);
                    f.SaveAs(UploadPath);
                    thongTin.HinhAnh = FileName;
                }
                db.ThongTins.AddOrUpdate(thongTin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(thongTin);
        }

        // GET: ThongTins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThongTin thongTin = db.ThongTins.Find(id);
            if (thongTin == null)
            {
                return HttpNotFound();
            }
            TaiKhoan tk=db.TaiKhoans.FirstOrDefault(g=>g.Id == thongTin.IdTK);
            db.TaiKhoans.Remove(tk);
            db.ThongTins.Remove(thongTin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

kiemketaisan/kiemketaisan/Views/NhanVien/Create.cshtml
@model kiemketaisan.Models.ThongTin

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var phong = ViewData["phong"] as List<kiemketaisan.Models.PhongBan>;
}

<h2>Thêm nhân viên mới</h2>

@using (Html.BeginForm("Create", "NhanVien", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Thông tin nhân viên</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="control-label col-md-2">Họ và tên</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Email</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Giới tính</div>
        <div class="col-md-10">
            <select class="form-control" name="GioiTinh">
                <option value="1">Nam</option>
                <option value="0">Nữ</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Ngày sinh</div>
        <div class="col-md-10">
            <input class="form-control" name="NgaySinh" type="date" />
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Địa chỉ</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Hình ảnh</div>
        <div class="col-md-10">
            <input type="file" name="Anh" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2">Tên đăng nhập</div>
        <div class="col-md-10">
            <input class="form-control" name="tendangnhap" />
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2">Mật khẩu</div>
        <div class="col-md-10">
            <input class="form-control" name="matkhau" />
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2">Phân quyền</div>
        <div class="col-md-10">
            <select class="form-control" name="phanquyen">
                <option value="1">Quản trị viên</option>
                <option value="2">Nhân viên</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2">Phòng ban</div>
        <div class="col-md-10">
            <select class="form-control" name="IdPB">
                @foreach(var item in phong)
                {
                    <option value="@item.Id">@item.TenPhongBan</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-1">
                <input type="submit" value="Thêm mới" class="btn btn-success" />
            </div>
            <div class="col-md-2">
                <a href="@Url.Action("Index","NhanVien")" style="margin-left:10px" class="btn btn-primary">Trở lại</a>
            </div>
        </div>
    </div>
</div>
}

kiemketaisan/kiemketaisan/Views/NhanVien/Edit.cshtml
@model kiemketaisan.Models.ThongTin

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var tk = ViewData["taikhoan"] as List<kiemketaisan.Models.TaiKhoan>;
    var pq = tk.FirstOrDefault(g => g.Id == Model.IdTK).PhanQuyen;
    var phong = ViewData["phong"] as List<kiemketaisan.Models.PhongBan>;
}

<h2>Sửa thông tin nhân viên</h2>

@using (Html.BeginForm("Edit", "NhanVien", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Thông tin nhân viên</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <input name="Id" value="@Model.Id" hidden />
    <input name="IdTK" value="@Model.IdTK" hidden />
    <input name="HinhAnh" value="@Model.HinhAnh" hidden />
    <div class="form-group">
        <div class="control-label col-md-2">Họ và tên</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Email</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Giới tính</div>
        <div class="col-md-10">
            <select class="form-control" name="GioiTinh">
                <option value="1">Nam</option>
                <option value="0">Nữ</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Ngày sinh</div>
        <div class="col-md-10">
            <input class="form-control" name="NgaySinh" type="date" value="@Model.NgaySinh.Value.ToString("yyyy-MM-dd")" />
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Địa chỉ</div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="control-label col-md-2">Hình ảnh</div>
        <div class="col-md-10">
            <input type="file" name="Anh" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2">Phân quyền</div>
        <div class="col-md-10">
            <select class="form-control" name="phanquyen">
                <option value="1" @(pq == 1 ? "selected" : "")>Quản trị viên</option>
                <option value="2" @(pq == 2 ? "selected" : "")>Nhân viên</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-md-2">Phòng ban</div>
        <div class="col-md-10">
            <select class="form-control" name="IdPB">
                @foreach (var item in phong)
                {
                    <option value="@item.Id" @(item.Id==Model.IdPB?"selected":"")>@item.TenPhongBan</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-1">
                <input type="submit" value="Cập nhật" class="btn btn-success" />
            </div>
            <div class="col-md-2">
                <a href="@Url.Action("Index","NhanVien")" style="margin-left:10px" class="btn btn-primary">Trở lại</a>
            </div>
        </div>
    </div>
</div>
}

kiemketaisan/kiemketaisan/Views/NhanVien/Index.cshtml
@model IEnumerable<kiemketaisan.Models.ThongTin>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var stt = 0;
    var phong = ViewData["phong"] as List<kiemketaisan.Models.PhongBan>;
}

<h2>
    Danh sách nhân viên
</h2>
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <p>
                    <a href="@Url.Action("Create","NhanVien")" class="btn btn-primary">Thêm mới</a>&nbsp;
                </p>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr class="text-center">
                                <th>STT</th>
                                <th>Họ và tên</th>
                                <th>Ảnh</th>
                                <th> Giới tính </th>
                                <th>Ngày sinh</th>
                                <th>Email</th>
                                <th>Địa chỉ</th>
                                @if (Session["PQ"].ToString() == "1")
                                {<th>
                                Phòng ban
                                </th>
                                }
                                    <th> Thao tác </th>
                                </tr>
                        </thead>
                        @foreach (var item in Model)
                        {
                            stt++;
                            <tr class="text-center">
                                <td>@stt</td>
                                <td>@item.HoTen</td>
                                <td><img src="~/upload/@item.HinhAnh" height="200" width="200"></td>
                                <td>@(item.GioiTinh==1?"Nam":"Nữ")</td>
                                <td>@item.NgaySinh.Value.ToString("dd/MM/yyyy")</td>
                                <td>@item.Email</td>
                                <td>@item.DiaChi</td>
                                @if (Session["PQ"].ToString() == "1")
                                {
                                    <td>
                                        @phong.FirstOrDefault(g=>g.Id==item.IdPB).TenPhongBan
                                    </td>
                                }
                                <td>
                                    <a href="@Url.Action("Edit","NhanVien",new {id=item.Id})" class="btn btn-success">Sửa</a> &nbsp;
                                    <a href="@Url.Action("Delete","NhanVien",new {id=item.Id})" class="btn btn-danger">Xóa</a>
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>