kiemketaisan/kiemketaisan/Models/PhongBan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiemketaisan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        public int Id { get; set; }
        public string TenPhongBan { get; set; }
    }
}

kiemketaisan/kiemketaisan/Controllers/PhongBanController.cs
using kiemketaisan.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace kiemketaisan.Controllers
{
    public class PhongBanController : Controller
    {
        private Data db = new Data();

        // GET: TaiSans
        public ActionResult Index(string search = "")
        {
            if (Session["Id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var list = db.PhongBans.AsQueryable();
            if (!string.IsNullOrEmpty(search))
            {
                list = list.Where(g => g.TenPhongBan.Contains(search));
            }
            return View(list.ToList());
        }

        // GET: TaiSans/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TenPhongBan")] PhongBan phongBan)
        {
            if (ModelState.IsValid)
            {
                db.PhongBans.Add(phongBan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(phongBan);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhongBan taiSan = db.PhongBans.Find(id);
            if (taiSan == null)
            {
                return HttpNotFound();
            }
            db.PhongBans.Remove(taiSan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhongBan taiSan = db.PhongBans.Find(id);
            if (taiSan == null)
            {
                return HttpNotFound();
            }
            return View(taiSan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TenPhongBan")] PhongBan taiSan)
        {
            if (ModelState.IsValid)
            {
                db.PhongBans.AddOrUpdate(taiSan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(taiSan);
        }
    }
}

kiemketaisan/kiemketaisan/Views/PhongBan/Create.cshtml
@model kiemketaisan.Models.PhongBan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>Thêm mới phòng ban</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Thông tin phòng ban</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="control-label col-md-2">Tên phòng ban</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenPhongBan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenPhongBan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-md-1">
                        <input type="submit" value="Thêm mới" class="btn btn-success" />
                    </div>
                    <div class="col-md-2">
                        <a href="@Url.Action("Index","PhongBan")" style="margin-left:10px" class="btn btn-primary">Trở lại</a>
                    </div>
                </div>
            </div>
        </div>
    }

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

kiemketaisan/kiemketaisan/Views/PhongBan/Edit.cshtml
@model kiemketaisan.Models.PhongBan

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>Sửa phòng ban</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Thông tin phòng ban</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="control-label col-md-2">Tên phòng ban</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenPhongBan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenPhongBan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-md-1">
                        <input type="submit" value="Cập nhật" class="btn btn-success" />
                    </div>
                    <div class="col-md-2">
                        <a href="@Url.Action("Index","PhongBan")" style="margin-left:10px" class="btn btn-primary">Trở lại</a>
                    </div>
                </div>
            </div>
        </div>
    }

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

kiemketaisan/kiemketaisan/Views/PhongBan/Index.cshtml
@model IEnumerable<kiemketaisan.Models.PhongBan>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var stt = 0;
}

<h2>
    Danh sách phòng ban
</h2>
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12" style="margin-bottom:10px">
                        <form action="/PhongBan/Index" method="get">
                            <input placeholder="Nhập từ khóa tìm kiếm" name="search" value="@Request["search"]" class="form-control" style="margin-bottom:10px" />
                            <button type="submit" class="btn btn-success">Tìm kiếm</button>

                            <a href="@Url.Action("Create", "PhongBan")" class="btn btn-primary">Thêm mới</a> @Html.Raw(" ")
                        </form>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr style="text-align:center">
                            <th  style="text-align:center">STT</th>
                            <th style="text-align:center">
                                Tên phòng ban
                            </th>
                            @if (Session["PQ"].ToString() == "1")
                            {
                                <th  style="text-align:center">Thao tác</th>
                            }
                        </tr>
                        @foreach (var item in Model)
                        {
                            stt++;
                            <tr class="text-center">
                                <td>@stt</td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenPhongBan)
                                </td>
                                <td style="display:flex;justify-content:center">

                                    <a href="@Url.Action("Index", "TaiSans", new { IdPB = item.Id })" class="btn btn-success">Quản lý</a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href="@Url.Action("Edit", "PhongBan", new { id = item.Id })" class="btn btn-success">Sửa</a> @Html.Raw(" ")
                                    <a href="@Url.Action("Delete", "PhongBan", new { id = item.Id })" class="btn btn-danger" style="margin-left:10px">Xóa</a>

                                </td>

                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>